apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-application
  namespace: web
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-application
  targetCPUUtilizationPercentage: 75
