apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-application
  name: sample-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-application
  template:
    metadata:
      labels:
        app: sample-application
    spec:
      containers:
      - image: <Account_ID>.dkr.ecr.ap-south-1.amazonaws.com/sample-application:latest
        name: authorization
        ports:
        - containerPort: 8000
