apiVersion: v1
kind: Service
metadata:
  name: sample-application-service
spec:
  type: ClusterIP
  selector:
    app: sample-application
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 
